# Generated by Django 2.2.6 on 2019-10-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191013_1308'),
        ('api', '0004_auto_20191013_1208'),
    ]

    operations = [
    ]
