# Generated by Django 2.2.6 on 2019-10-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20191013_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availibility',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
