# Generated by Django 2.2.6 on 2019-10-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191014_1239'),
        ('api', '0005_merge_20191014_0839'),
    ]

    operations = [
    ]
