# Generated by Django 2.2.6 on 2019-10-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_basket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_ref',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
