# Generated by Django 2.2.6 on 2019-10-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_order_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_ref',
        ),
    ]
