# Generated by Django 2.2.6 on 2019-10-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191019_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_ref',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
