# Generated by Django 2.2.6 on 2019-10-20 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191020_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='item',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_per_order',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
