# Generated by Django 2.2.6 on 2019-10-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191020_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='price',
        ),
    ]
