# Generated by Django 2.2.6 on 2019-10-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191023_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, choices=[('Kuwait', 'Kuwait'), ('Lebanon', 'Lebanon'), ('Egypt', 'Egypt'), ('Yemen', 'Yemen')], max_length=50, null=True),
        ),
    ]
