# Generated by Django 2.2.6 on 2019-10-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
